# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: AlexGladkov.Yashik
PackageVersion: 0.2.1
Platform:
- Windows.Desktop
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: yashik.exe
    PortableCommandAlias: yashik
  InstallerUrl: "https://github.com/AlexGladkov/Yashik/releases/download/v0.2.1/yashik-windows-x86_64.zip"
  InstallerSha256: "DEDBAF98ED1816BF02103B7F9F3E5F5358248B8CCE8898A3F03AF6AE7F878258"
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: yashik.exe
    PortableCommandAlias: yashik
  InstallerUrl: "https://github.com/AlexGladkov/Yashik/releases/download/v0.2.1/yashik-windows-aarch64.zip"
  InstallerSha256: "67CE7D8CA4E87ADA7E192CA9258D58B4F8EE09091423AAFF9CB73BC1BFAF5368"
ManifestType: installer
ManifestVersion: 1.10.0
